spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/napd_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234 # <--- 컨테이너에 설정한 비밀번호 (1234)
  jpa:
    hibernate:
      ddl-auto: update # 개발 시 편리한 스키마 자동 생성/업데이트 설정
    show-sql: true # 콘솔에 실행되는 SQL을 보여줍니다.
    properties:
      hibernate:
        format_sql: true
jwt:
  # Base64 인코딩된 32바이트(256비트) 이상의 Secret Key를 사용해야 안전합니다.
  # 임시로 이 긴 문자열을 사용하겠습니다.
  secret: c3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXktbmFwZC1iYWNrZW5kLXByb2plY3Q=